<?php
return [

  'key' => [
      'C', 
      'C#', 
      'D',
      'Db',
      'D#', 
      'Eb', 
      'E', 
      'F', 
      'F#', 
      'G',
      'Gb', 
      'Ab',
      'G#', 
      'A',
      'A#', 
      'Bb', 
      'B'
  ],

  'scale' => [
      'major',
      'minor',
      'Major',
      'Minor',
      'min',
      'maj'
  ],

  'genres' => [
      'hip-hop',
      'rnb',
      'house',
      'pop',
      'trap',
      'soul',
      'deep house',
      'techno',
      'edm',
      'tech house',
      'rock',
      'funk',
      'downtempo',
      'lo-fi',
      'lo-fi hip-hop',
      'cinematic',
      'jazz',
      'synthwave',
      'future bass',
      'neo soul',
      'afropop & afrobeats',
      'boom bap',
      'uk garage',
      'indie rock',
      'progressive house',
      'reggaeton',
      'disco',
      'dancehall',
      'dubstep',
      'drum and bass',
      'ambient',
      'indie dance',
      'trance',
      'experimental',
      'drill',
      'folk',
      'future house',
      'heavy metal',
      'indie pop',
      'hyperpop',
      'uk drill',
      'electro',
      'tearout dubstep',
      'synth-pop',
      'breakbeat',
      'minimal techno',
    
  ],

  'instruments' => [
    'drums',
    'synth',
    'live sounds',
    'guitar',
    'keys',
    'hats',
    'percussion',
    'snares',
    'vocals',
    'kicks',
    'piano',
    'electric guitar',
    'toms',
    'rims',
    '808',
    'electric piano',
    'claps',
    'shakers',
    'cymbals',
    'crash',
    'juno',
    'bass',
    'bass guitar',
    
  ],

  'type' => [
    'loop',
    'one-shot'
  ]

];